name: Build
on:
  workflow_dispatch:

jobs:

  build:
    name: "build list"
    runs-on: ubuntu-latest
    steps:
      
      - name: "setup py"
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: "Checkout GScan"
        uses: actions/checkout@v2
        with:
          repository: grayddq/GScan

      - run: |

          python3 ../run.py > ../gscan-list.domains
          cd ..

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gscan-list.domains
          git push
          git push --tags
